[Settings]
; Текст для спама
text = Привет!

; Задержка между сообщениями (секунды)
; 0.3 - быстро, 0.5 - нормально, 1.0 - медленно
delay = 1.0

; Задержка перед стартом (сек), чтобы успеть переключиться в Telegram
start_delay = 5

; Сколько раз отправить (0 = бесконечно)
; 0 - бесконечно
; 100 - отправить 100 раз и остановиться
max_messages = 5

; Сохранять логи (True/False)
save_logs = False